# Generated by Django 2.1.5 on 2019-03-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0002_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='music.Artist'),
        ),
    ]
