# Generated by Django 2.1.5 on 2019-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0003_auto_20190302_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
