# Generated by Django 2.1.5 on 2019-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0009_auto_20190303_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='music.Artist'),
        ),
    ]
