# Generated by Django 2.1.5 on 2019-03-03 18:49

from django.db import migrations, models
import django.db.migrations.migration
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20190304_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ManyToManyField(related_name='song', to='music.Artist')),
            ],
            bases=(models.Model, django.db.migrations.migration.Migration),
        ),
    ]
