# Generated by Django 2.1.5 on 2019-03-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_remove_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
