# Generated by Django 2.1.5 on 2019-03-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_remove_song_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
