# Generated by Django 2.1.5 on 2019-03-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Song',
        ),
    ]
