# Generated by Django 2.1.5 on 2019-03-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20190304_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
