# Generated by Django 2.1.5 on 2019-03-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
    ]
