# Generated by Django 2.1.5 on 2019-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_remove_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
