# Generated by Django 2.1.5 on 2019-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
    ]
