# Generated by Django 2.1.5 on 2019-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
