# Generated by Django 2.1.5 on 2019-03-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20190308_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
