# Generated by Django 2.1.5 on 2019-03-15 11:16

from django.db import migrations


def add_song(apps, scheme_editor):
    Song = apps.get_model('music', 'Song')
    Album = apps.get_model('music', 'Album')
    Artist = apps.get_model('music', 'Artist')
    db_alias = scheme_editor.connection.alias
    a = Album.objects.using(db_alias).get(album_title='Halcyon')
    b = Artist.objects.using(db_alias).filter(name='Ellie Goulding')
    c = Song.objects.using(db_alias).create(song_title='Explosions', album=a, slug='explosion')
    c.artist_name.set(b)


def delete_song(apps, scheme_editor):
    Song = apps.get_model('music', 'Song')
    db_alias = scheme_editor.connection.alias
    Song.objects.using(db_alias).get(song_title='Explosions').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20190311_2100'),
    ]

    operations = [
        migrations.RunPython(add_song, delete_song)
    ]
